# Generated by Django 6.0.5 on 2026-05-15 10:55

import candidatures.models
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type_doc",
                    models.CharField(
                        choices=[
                            ("DIPLOME", "Diplôme"),
                            ("RELEVE", "Relevé de notes"),
                            ("CIN", "Carte d'identité nationale"),
                            ("PHOTO", "Photo d'identité"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        upload_to=candidatures.models.upload_document_path
                    ),
                ),
                ("taille_ko", models.PositiveIntegerField(blank=True, null=True)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                (
                    "qualite_ocr",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("date_upload", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Document",
                "db_table": "documents",
            },
        ),
        migrations.CreateModel(
            name="Dossier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("EN_TRAITEMENT", "En traitement"),
                            ("INCOMPLET", "Incomplet"),
                            ("SUSPECT", "Suspect (vérification manuelle)"),
                            ("REJETE_AUTO", "Rejeté automatiquement"),
                            ("EN_ATTENTE", "En attente de décision"),
                            ("PRESELECTIONNE", "Présélectionné"),
                            ("REJETE_FINAL", "Rejeté (décision finale)"),
                        ],
                        default="BROUILLON",
                        max_length=20,
                    ),
                ),
                ("diplome_obtenu", models.CharField(max_length=200)),
                ("etablissement_origine", models.CharField(max_length=300)),
                ("annee_obtention", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "mention",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TB", "Très Bien"),
                            ("B", "Bien"),
                            ("AB", "Assez Bien"),
                            ("P", "Passable"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "moyenne_generale",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("classement", models.PositiveIntegerField(blank=True, null=True)),
                ("motif_rejet", models.TextField(blank=True)),
                (
                    "score_confiance_ocr",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("is_suspect", models.BooleanField(default=False)),
                ("date_soumission", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Dossier",
                "db_table": "dossiers",
                "ordering": ["-score", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="NoteMatiere",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("matiere", models.CharField(max_length=100)),
                (
                    "note_declaree",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "note_extraite",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "ecart",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("is_suspect", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Note par Matière",
                "db_table": "notes_matieres",
            },
        ),
    ]
