# Generated by Django 6.0.5 on 2026-05-15 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("administration", "0002_initial"),
        ("candidatures", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dossier",
            name="candidat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dossiers",
                to="users.candidat",
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="filiere",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dossiers",
                to="administration.filiere",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="dossier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="candidatures.dossier",
            ),
        ),
        migrations.AddField(
            model_name="notematiere",
            name="dossier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="candidatures.dossier",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dossier",
            unique_together={("candidat", "filiere")},
        ),
        migrations.AlterUniqueTogether(
            name="document",
            unique_together={("dossier", "type_doc")},
        ),
        migrations.AlterUniqueTogether(
            name="notematiere",
            unique_together={("dossier", "matiere")},
        ),
    ]
