# Generated by Django 4.2 on 2026-05-21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("candidatures", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dossier",
            unique_together=set(),
        ),
    ]
