# Generated by Django 4.2 on 2026-05-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidatures", "0003_remove_dossier_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="dossier",
            name="alertes_verification",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Liste des alertes détectées lors de la vérification",
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="cne",
            field=models.CharField(
                blank=True, help_text="Code National de l'Étudiant", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="code_massar",
            field=models.CharField(
                blank=True, help_text="Code Massar du candidat", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="massar_verifie",
            field=models.BooleanField(
                default=False, help_text="Vérification Massar confirmée manuellement"
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="score_authenticite",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Score global d'authenticité des documents 0.0→1.0",
                max_digits=3,
                null=True,
            ),
        ),
    ]
