# Generated by Django 4.2 on 2026-05-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidatures", "0004_add_verification_fields_to_dossier"),
    ]

    operations = [
        migrations.AddField(
            model_name="dossier",
            name="rang_final",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dossier",
            name="score_final",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Score final combiné dossier + épreuve écrite",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dossier",
            name="statut",
            field=models.CharField(
                choices=[
                    ("BROUILLON", "Brouillon"),
                    ("EN_TRAITEMENT", "En traitement"),
                    ("INCOMPLET", "Incomplet"),
                    ("SUSPECT", "Suspect (vérification manuelle)"),
                    ("REJETE_AUTO", "Rejeté automatiquement"),
                    ("EN_ATTENTE", "En attente de décision"),
                    ("PRESELECTIONNE", "Présélectionné"),
                    ("REJETE_FINAL", "Rejeté (décision finale)"),
                    ("ADMIS_FINAL", "Admis définitivement"),
                    ("RECALE_FINAL", "Recalé à l'épreuve écrite"),
                    ("ABSENT_ECRIT", "Absent à l'épreuve écrite"),
                ],
                default="BROUILLON",
                max_length=20,
            ),
        ),
    ]
