# Generated by Django 4.2 on 2026-06-03 15:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("candidatures", "0005_add_epreuve_ecrite_and_note_ecrite"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notematiere",
            options={"verbose_name": "Note par Matière (legacy)"},
        ),
        migrations.CreateModel(
            name="NoteSemestre",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "semestre",
                    models.CharField(
                        choices=[
                            ("S1", "Semestre 1"),
                            ("S2", "Semestre 2"),
                            ("S3", "Semestre 3"),
                            ("S4", "Semestre 4"),
                            ("S5", "Semestre 5"),
                            ("S6", "Semestre 6"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "moyenne",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Moyenne du semestre sur 20",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "session",
                    models.CharField(
                        choices=[
                            ("NORMALE", "Session Normale"),
                            ("RATTRAPAGE", "Session de Rattrapage"),
                        ],
                        default="NORMALE",
                        max_length=12,
                    ),
                ),
                (
                    "mention",
                    models.CharField(
                        choices=[
                            ("TRES_BIEN", "Très Bien"),
                            ("BIEN", "Bien"),
                            ("ASSEZ_BIEN", "Assez Bien"),
                            ("PASSABLE", "Passable"),
                        ],
                        default="PASSABLE",
                        max_length=12,
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes_semestres",
                        to="candidatures.dossier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Note par Semestre",
                "verbose_name_plural": "Notes par Semestre",
                "db_table": "notes_semestres",
                "ordering": ["semestre"],
                "unique_together": {("dossier", "semestre")},
            },
        ),
    ]
