# Generated by Django 6.0.5 on 2026-06-04 23:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidatures", "0006_alter_notematiere_options_notesemestre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dossier",
            name="massar_verifie",
        ),
        migrations.AlterField(
            model_name="notesemestre",
            name="mention",
            field=models.CharField(
                choices=[
                    ("TRES_BIEN", "Très Bien"),
                    ("BIEN", "Bien"),
                    ("ASSEZ_BIEN", "Assez Bien"),
                    ("PASSABLE", "Passable"),
                ],
                editable=False,
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="notesemestre",
            name="moyenne",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Moyenne du semestre sur 20 (entre 10 et 20)",
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(10),
                    django.core.validators.MaxValueValidator(20),
                ],
            ),
        ),
    ]
