# Generated by Django 6.0.5 on 2026-06-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidatures", "0007_remove_dossier_massar_verifie_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dossier",
            name="statut",
            field=models.CharField(
                choices=[
                    ("BROUILLON", "Brouillon"),
                    ("EN_TRAITEMENT", "En traitement"),
                    ("INCOMPLET", "Incomplet"),
                    ("SUSPECT", "Suspect (vérification manuelle)"),
                    ("REJETE_AUTO", "Rejeté automatiquement"),
                    ("EN_ATTENTE", "En attente de décision"),
                    ("PRESELECTIONNE", "Présélectionné"),
                    ("REJETE_FINAL", "Rejeté (décision finale)"),
                    ("ADMIS_FINAL", "Admis définitivement"),
                    ("RECALE_FINAL", "Recalé à l'épreuve écrite"),
                    ("ABSENT_ECRIT", "Absent à l'épreuve écrite"),
                    ("CONVOQUE_ORAL", "Convoqué à l'épreuve orale"),
                    ("ORAL_ACCEPTE", "Accepté après entretien oral"),
                    ("ORAL_REFUSE", "Refusé après entretien oral"),
                    ("INSCRIT", "Inscrit définitivement à l'ENSA BM"),
                ],
                default="BROUILLON",
                max_length=25,
            ),
        ),
    ]
