# Generated by Django 6.0.5 on 2026-05-15 10:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Filiere",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "niveau",
                    models.CharField(
                        choices=[("BAC2", "Bac+2"), ("BAC3", "Bac+3")], max_length=10
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("places_disponibles", models.PositiveIntegerField(default=30)),
                ("is_active", models.BooleanField(default=True)),
                ("date_ouverture", models.DateTimeField(blank=True, null=True)),
                ("date_fermeture", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Filière",
                "db_table": "filieres",
                "ordering": ["niveau", "nom"],
            },
        ),
        migrations.CreateModel(
            name="HistoriqueAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("SOUMISSION", "Soumission dossier"),
                            ("VALIDATION", "Validation responsable"),
                            ("REJET_AUTO", "Rejet automatique"),
                            ("REJET_MANUEL", "Rejet manuel"),
                            ("PRESELECTION", "Présélection"),
                            ("COMPLEMENT", "Demande complément"),
                            ("MODIFICATION", "Modification dossier"),
                        ],
                        max_length=50,
                    ),
                ),
                ("commentaire", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Action",
                "db_table": "historique_actions",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DiplomaAccepte",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom_diplome", models.CharField(max_length=200)),
                ("etablissements", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "filiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diplomes_acceptes",
                        to="administration.filiere",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diplôme Accepté",
                "db_table": "diplomes_acceptes",
            },
        ),
    ]
