# Generated by Django 4.2 on 2026-05-30 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("candidatures", "0005_add_epreuve_ecrite_and_note_ecrite"),
        ("administration", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EpreuveEcrite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Ex : Épreuve écrite — GIR Bac+2 — Session 2025",
                        max_length=200,
                    ),
                ),
                ("date_epreuve", models.DateField(blank=True, null=True)),
                (
                    "seuil_admission",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        help_text="Note minimale pour être admis",
                        max_digits=5,
                    ),
                ),
                (
                    "note_sur",
                    models.DecimalField(
                        decimal_places=2,
                        default=20.0,
                        help_text="Barème de l'épreuve (20, 40, 100...)",
                        max_digits=5,
                    ),
                ),
                (
                    "coefficient",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Coefficient dans le score final",
                        max_digits=5,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("NON_COMMENCEE", "Non commencée"),
                            ("EN_COURS", "En cours"),
                            ("NOTES_IMPORTEES", "Notes importées"),
                            ("RESULTATS_PUBLIES", "Résultats publiés"),
                        ],
                        default="NON_COMMENCEE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="epreuves_creees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "filiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="epreuves",
                        to="administration.filiere",
                    ),
                ),
            ],
            options={
                "verbose_name": "Épreuve Écrite",
                "db_table": "epreuves_ecrites",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="historiqueaction",
            name="dossier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historique",
                to="candidatures.dossier",
            ),
        ),
        migrations.CreateModel(
            name="NoteEcrite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "note",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "resultat",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ADMIS", "Admis"),
                            ("RECALE", "Recalé"),
                            ("ABSENT", "Absent"),
                            ("ANNULE", "Note annulée"),
                        ],
                        max_length=10,
                    ),
                ),
                ("rang_final", models.PositiveIntegerField(blank=True, null=True)),
                ("note_importee_le", models.DateTimeField(blank=True, null=True)),
                (
                    "ligne_excel",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Numéro de ligne dans le fichier Excel source",
                        null=True,
                    ),
                ),
                (
                    "import_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash MD5 du fichier Excel importé",
                        max_length=64,
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes_ecrits",
                        to="candidatures.dossier",
                    ),
                ),
                (
                    "epreuve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="administration.epreuveecrite",
                    ),
                ),
            ],
            options={
                "verbose_name": "Note Écrite",
                "db_table": "notes_ecrites",
                "ordering": ["-note"],
                "unique_together": {("epreuve", "dossier")},
            },
        ),
    ]
