# Generated by Django 6.0.5 on 2026-05-31 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0003_add_epreuve_ecrite_and_note_ecrite"),
    ]

    operations = [
        migrations.AddField(
            model_name="epreuveecrite",
            name="date_oral",
            field=models.DateField(
                blank=True, help_text="Date de l'épreuve orale", null=True
            ),
        ),
    ]
