# Generated by Django 6.0.5 on 2026-05-31 00:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0004_epreuveecrite_date_oral"),
    ]

    operations = [
        migrations.AddField(
            model_name="epreuveecrite",
            name="heure_oral",
            field=models.CharField(
                blank=True,
                help_text="Heure de l'épreuve orale",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="epreuveecrite",
            name="lieu_oral",
            field=models.CharField(
                blank=True,
                help_text="Lieu de l'épreuve orale",
                max_length=255,
                null=True,
            ),
        ),
    ]
