# Generated by Django 6.0.5 on 2026-05-31 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0005_epreuveecrite_heure_oral_epreuveecrite_lieu_oral"),
    ]

    operations = [
        migrations.AddField(
            model_name="filiere",
            name="date_ecrit",
            field=models.DateField(
                blank=True, help_text="Date de l'épreuve écrite", null=True
            ),
        ),
        migrations.AddField(
            model_name="filiere",
            name="heure_ecrit",
            field=models.CharField(
                blank=True,
                help_text="Heure de l'épreuve écrite (ex: 09:00)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="filiere",
            name="lieu_ecrit",
            field=models.CharField(
                blank=True,
                help_text="Lieu de l'épreuve écrite",
                max_length=255,
                null=True,
            ),
        ),
    ]
