# Generated by Django 6.0.5 on 2026-05-31 01:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0006_add_ecrit_fields_to_filiere"),
    ]

    operations = [
        migrations.AddField(
            model_name="filiere",
            name="date_oral",
            field=models.DateField(
                blank=True, help_text="Date de l'épreuve orale", null=True
            ),
        ),
        migrations.AddField(
            model_name="filiere",
            name="heure_oral",
            field=models.CharField(
                blank=True,
                help_text="Heure de l'épreuve orale (ex: 09:00)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="filiere",
            name="lieu_oral",
            field=models.CharField(
                blank=True,
                help_text="Lieu de l'épreuve orale",
                max_length=255,
                null=True,
            ),
        ),
    ]
