# Generated by Django 6.0.5 on 2026-06-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0007_add_oral_fields_to_filiere"),
    ]

    operations = [
        migrations.AddField(
            model_name="diplomaaccepte",
            name="coefficient",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="Coefficient multiplicateur pour le score du diplôme",
                max_digits=3,
            ),
        ),
        migrations.AddField(
            model_name="filiere",
            name="coef_autre_diplome",
            field=models.DecimalField(
                decimal_places=2,
                default=0.8,
                help_text="Coefficient appliqué aux diplômes 'Autre'",
                max_digits=3,
            ),
        ),
    ]
