# Generated by Django 6.0.5 on 2026-06-10 09:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0008_diplomaaccepte_coefficient_and_more"),
        ("candidatures", "0008_add_epreuve_orale_convocation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EpreuveOrale",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Ex : Entretien oral — TDI Bac+2 — 2025",
                        max_length=200,
                    ),
                ),
                ("date_oral", models.DateField(blank=True, null=True)),
                ("heure_debut", models.TimeField(blank=True, null=True)),
                (
                    "lieu",
                    models.CharField(
                        default="Salle des conférences — ENSA BM", max_length=300
                    ),
                ),
                (
                    "duree_minutes",
                    models.PositiveIntegerField(
                        default=20, help_text="Durée de chaque entretien en minutes"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("PLANIFIEE", "Planifiée"),
                            ("EN_COURS", "En cours"),
                            ("TERMINEE", "Terminée"),
                            ("RESULTATS_PUBLIES", "Résultats publiés"),
                        ],
                        default="PLANIFIEE",
                        max_length=25,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="epreuves_oral_creees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "epreuve_ecrite",
                    models.ForeignKey(
                        blank=True,
                        help_text="Épreuve écrite liée",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="epreuves_oral",
                        to="administration.epreuveecrite",
                    ),
                ),
                (
                    "filiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="epreuves_oral",
                        to="administration.filiere",
                    ),
                ),
            ],
            options={
                "verbose_name": "Épreuve Orale",
                "db_table": "epreuves_orales",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConvocationOrale",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "heure_passage",
                    models.TimeField(
                        blank=True,
                        help_text="Calculée automatiquement : heure_debut + (rang × duree_minutes)",
                        null=True,
                    ),
                ),
                (
                    "numero_passage",
                    models.PositiveIntegerField(
                        help_text="Ordre de passage dans la journée", null=True
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente de décision"),
                            ("ACCEPTE", "Accepté"),
                            ("REFUSE", "Refusé"),
                            ("ABSENT", "Absent à l'oral"),
                        ],
                        default="EN_ATTENTE",
                        max_length=15,
                    ),
                ),
                (
                    "commentaire_jury",
                    models.TextField(
                        blank=True,
                        help_text="Note interne du jury (jamais visible au candidat)",
                    ),
                ),
                ("date_decision", models.DateTimeField(blank=True, null=True)),
                ("bac_verifie", models.BooleanField(default=False)),
                ("diplome_verifie", models.BooleanField(default=False)),
                ("releve_notes_verifie", models.BooleanField(default=False)),
                ("cin_verifie", models.BooleanField(default=False)),
                ("dossier_complet", models.BooleanField(default=False)),
                ("convocation_generee", models.BooleanField(default=False)),
                (
                    "convocation_pdf",
                    models.FileField(blank=True, null=True, upload_to="convocations/"),
                ),
                ("date_generation", models.DateTimeField(blank=True, null=True)),
                (
                    "decide_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decisions_oral",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="convocations_oral",
                        to="candidatures.dossier",
                    ),
                ),
                (
                    "epreuve_oral",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="convocations",
                        to="administration.epreuveorale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Convocation Orale",
                "db_table": "convocations_orales",
                "ordering": ["numero_passage"],
                "unique_together": {("epreuve_oral", "dossier")},
            },
        ),
    ]
