# Generated by Django 6.0.5 on 2026-06-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0009_add_epreuve_orale_convocation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="epreuveecrite",
            name="date_epreuve",
        ),
        migrations.RemoveField(
            model_name="epreuveecrite",
            name="date_oral",
        ),
        migrations.RemoveField(
            model_name="epreuveecrite",
            name="heure_oral",
        ),
        migrations.RemoveField(
            model_name="epreuveecrite",
            name="lieu_oral",
        ),
        migrations.RemoveField(
            model_name="epreuveorale",
            name="date_oral",
        ),
        migrations.RemoveField(
            model_name="epreuveorale",
            name="heure_debut",
        ),
        migrations.RemoveField(
            model_name="epreuveorale",
            name="lieu",
        ),
        migrations.RemoveField(
            model_name="filiere",
            name="heure_ecrit",
        ),
        migrations.RemoveField(
            model_name="filiere",
            name="heure_oral",
        ),
        migrations.AlterField(
            model_name="filiere",
            name="date_ecrit",
            field=models.DateTimeField(
                blank=True, help_text="Date et heure de l'épreuve écrite", null=True
            ),
        ),
        migrations.AlterField(
            model_name="filiere",
            name="date_oral",
            field=models.DateTimeField(
                blank=True, help_text="Date et heure de l'épreuve orale", null=True
            ),
        ),
    ]
