# Generated by Django 6.0.5 on 2026-05-15 10:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "destinataire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "type_notif",
                    models.CharField(
                        choices=[
                            ("SOUMISSION", "Confirmation soumission"),
                            ("REJET_AUTO", "Rejet automatique"),
                            ("REJET_MANUEL", "Rejet par responsable"),
                            ("PRESELECTION", "Présélection"),
                            ("INCOMPLET", "Dossier incomplet"),
                            ("COMPLEMENT", "Demande de complément"),
                        ],
                        max_length=30,
                    ),
                ),
                ("sujet", models.CharField(max_length=300)),
                ("contenu_html", models.TextField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("ENVOYEE", "Envoyée"),
                            ("ECHEC", "Échec d'envoi"),
                        ],
                        default="EN_ATTENTE",
                        max_length=15,
                    ),
                ),
                ("envoyee_le", models.DateTimeField(blank=True, null=True)),
                ("erreur", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Notification",
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
