# Generated by Django 6.0.5 on 2026-05-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="lue",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="lue_le",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
