# Generated by Django 4.2 on 2026-05-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_notification_lue_notification_lue_le"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type_notif",
            field=models.CharField(
                choices=[
                    ("SOUMISSION", "Confirmation soumission"),
                    ("REJET_AUTO", "Rejet automatique"),
                    ("REJET_MANUEL", "Rejet par responsable"),
                    ("PRESELECTION", "Présélection"),
                    ("INCOMPLET", "Dossier incomplet"),
                    ("COMPLEMENT", "Demande de complément"),
                    ("ADMIS_FINAL", "Admis définitivement"),
                    ("RECALE_FINAL", "Recalé à l'épreuve écrite"),
                ],
                max_length=30,
            ),
        ),
    ]
