# Generated by Django 6.0.5 on 2026-05-15 10:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("administration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigScoring",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("matiere", models.CharField(max_length=100)),
                ("poids", models.DecimalField(decimal_places=2, max_digits=5)),
                ("bonus_mention", models.JSONField(blank=True, default=dict)),
                (
                    "filiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_scoring",
                        to="administration.filiere",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration Scoring",
                "db_table": "config_scoring",
                "unique_together": {("filiere", "matiere")},
            },
        ),
        migrations.CreateModel(
            name="RegleRejet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type_regle",
                    models.CharField(
                        choices=[
                            ("DIPLOME_INVALIDE", "Diplôme non accepté"),
                            ("MOYENNE_INSUFFISANTE", "Moyenne générale insuffisante"),
                            ("NOTE_ELIMINATOIRE", "Note éliminatoire dans une matière"),
                            ("ETABLISSEMENT_INVALIDE", "Établissement non reconnu"),
                            ("DOUBLON_CIN", "Doublon CIN détecté"),
                            ("DATE_INCOHERENTE", "Incohérence date diplôme"),
                            ("DOCUMENT_MANQUANT", "Document obligatoire manquant"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("message_rejet", models.TextField()),
                ("parametre", models.JSONField(blank=True, default=dict)),
                (
                    "filiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regles",
                        to="administration.filiere",
                    ),
                ),
            ],
            options={
                "verbose_name": "Règle de Rejet",
                "db_table": "regles_rejet",
                "unique_together": {("filiere", "type_regle")},
            },
        ),
    ]
